# Generated by Django 4.0.6 on 2022-09-02 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transit_id', models.CharField(max_length=28, unique=True)),
                ('route', models.CharField(max_length=100)),
                ('boarding_time', models.DateTimeField()),
                ('available_seats', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField(unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('payment_ref', models.CharField(max_length=8)),
                ('status', models.CharField(choices=[('Boarded', 'Boarded'), ('Missed', 'Missed'), ('Unboarded', 'Unboarded')], default='Unboarded', max_length=20)),
                ('bookee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.bookee')),
                ('transit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.transit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
